apiVersion: v1
kind: Pod
metadata:
  name: invalid-no-requests
spec:
  containers:
    - name: app
      image: nginx:1.25
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
