apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: disallow-host-namespaces
spec:
  steps:
    - name: 01 - Apply policy
      try:
        - apply:
            file: ../policy.yaml
    - name: 02 - Wait for policy to be ready
      try:
        - assert:
            resource:
              apiVersion: kyverno.io/v1
              kind: ClusterPolicy
              metadata:
                name: disallow-host-namespaces
              status:
                conditions:
                  - reason: Succeeded
                    status: "True"
                    type: Ready
    - name: 03 - Pod without host namespaces should be admitted
      try:
        - apply:
            file: valid-pod.yaml
            expect:
              - check:
                  ($error == null): true
    - name: 04 - Pod with hostPID should be blocked
      try:
        - apply:
            file: invalid-host-pid.yaml
            expect:
              - check:
                  ($error != null): true
    - name: 05 - Pod with hostNetwork should be blocked
      try:
        - apply:
            file: invalid-host-network.yaml
            expect:
              - check:
                  ($error != null): true
    - name: 06 - Pod with hostIPC should be blocked
      try:
        - apply:
            file: invalid-host-ipc.yaml
            expect:
              - check:
                  ($error != null): true
